export enum NotificationType {
  FRIEND_REQUEST = 'FRIEND_REQUEST',
  FRIEND_ACCEPTED = 'FRIEND_ACCEPTED',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
  GROUP_INVITE = 'GROUP_INVITE',
  GROUP_MESSAGE = 'GROUP_MESSAGE',
  SYSTEM = 'SYSTEM',
}
